---
 - name: install java using yum
   yum: name={{ item }} state=present
   with_items:
    - java-11-openjdk.x86_64 
    - java-11-openjdk-demo.x86_64 
    - java-11-openjdk-devel.x86_64 
    - java-11-openjdk-headless.x86_64
