---
 - hosts: localhost
   vars:
    ansible_python_interpreter: /usr/bin/python3.6
   tasks:
     - name: create namespace
       k8s:
         name: my-namespace
         api_version: v1
         kind: Namespace
         state: present
