---
 - hosts: localhost
   vars:
    ansible_python_interpreter: /usr/bin/python3.6
   tasks:
    - name: deploy a web server
      k8s:
        api_version: v1
        namespace: my-namespace
        definition:
          kind: Deployment
          metadata:
            labels:
              app: nginx
            name: testing-service-deploy
          spec:
            replicas: 2
            selector:
              matchLabels:
                app: testing-service
            template:
              metadata:
                labels:
                  app: testing-service
              spec:
                containers:
                  - name: my-webserver
                    image: docker.io/jagadesh1982/testing-service:latest
                    ports:
                      - containerPort: 80
                        protocol: TCP
